apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-byo-test1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-lyoon-dh/chatbot-byo-test1:2dd165cb8be46806ae218a77daf14934fb00ba64@sha256:29d799dc75e432c1280df290e9ad26a4f191546aebeef9ad2979d25ec82fbc47 # use pre-built to bootstrap
          name: app-inference
