apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-byo-test1-model-config
data:
  MODEL_ENDPOINT: "https://meta-llama-31-8b-3scale-apicast-production.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com:443"
  MODEL_NAME: "redhataillama-31-8b-instruct"
